### ISSUE TITLE
Adding Lexe to our BDK Users webpage

### ISSUE THREAD

**Issue by thunderbiscuit** [lexe-app/lexe-public#69]
Hi there! I'm thunderbiscuit, I work on the core BDK team (mostly on language bindings). We're building a page on our website that includes projects that use BDK similar to the LDK one, and I'm reaching out to know if you'd be ok with us adding you there! You can take a look at the page on our website here: https://bitcoindevkit.org/case-studies/

Thank you!

**Comment by MaxFangX** [comment]
@thunderbiscuit yes, please do! Let us know if you need help with the description!

**Comment by thunderbiscuit** [comment]
Awesome. I'll open the PR adding a few projects next week and link to this issue. You'll be able to take a look at the preview before I merge. I was thinking of reusing what you have on the LDK page, but happy to use something else as well if you prefer.

**Comment by MaxFangX** [comment]
Heya @thunderbiscuit, appreciate you putting us up there! I noticed that our logo is almost unreadable in light mode due to the transparent background:

![Screen Shot 2024-04-09 at 12 14 55 PM](https://github.com/lexe-app/lexe-public/assets/7884003/79b831a6-5691-44f1-95a6-b2222edd70d2)

Would you mind updating it to the following?

![Lexe logo dark rectangular](https://github.com/lexe-app/lexe-public/assets/7884003/6783a14a-5b83-457c-9665-723433177bff)

Thanks!

**Comment by thunderbiscuit** [comment]
Of course!

**Comment by MaxFangX** [comment]
Thank you so much @thunderbiscuit!
